package com.jankowski.rafal.dancebook.frontend

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource

/**
 * Guards the one Tailwind failure mode nothing else in this suite can see.
 *
 * Tailwind emits a rule only for class names it finds in a scanned source. Every rendering
 * test here asserts on HTML, which a CSS-generation regression leaves untouched — so if
 * `output.css` silently loses a class, the calendar chips render unstyled and the whole
 * build is still green.
 *
 * The classes below are the ones with no second source of truth: they are built at runtime
 * in the `static/js` scripts or in Kotlin, and appear in no Thymeleaf template. They exist in the
 * stylesheet only because `input.css` names those directories in an `@source` glob. Delete
 * one of those globs and these are the assertions that fail.
 */
class TailwindOutputCssTest {

    private val css: String by lazy {
        val url = javaClass.getResource("/static/css/output.css")
            ?: error(
                "static/css/output.css is missing from the classpath. It is generated by the " +
                    "buildTailwind Gradle task, which processResources depends on — run ./gradlew build."
            )
        url.readText()
    }

    @Test
    fun `the stylesheet is built and non-trivial`() {
        assertTrue(
            css.length > 20_000,
            "output.css is only ${css.length} bytes, which means the Tailwind build produced a stub."
        )
    }

    @ParameterizedTest(name = "{0} survives into output.css")
    @ValueSource(
        strings = [
            // training-calendar.js builds every chip, day dot and agenda row by hand.
            "tc-chip", "tc-chip-struck", "tc-chip-time", "tc-chip-title", "tc-chip-styles",
            "tc-daydots", "tc-daydot", "tc-agenda-empty",
            // Utilities applied only from JS: main.js collapsibles, guided-figure-edit.js
            // toasts, training-calendar.js cancelled-session styling.
            "max-h-[1000px]", "max-h-[500px]", "line-through", "border-solid", "z-9999",
            // NotificationController renders the unread badge as an HTML string in Kotlin.
            "min-w-[18px]", "h-[18px]",
        ]
    )
    fun `a class built outside the templates still has a rule`(className: String) {
        assertTrue(
            css.contains(".${cssEscape(className)}"),
            "`$className` has no rule in output.css. It is generated outside the Thymeleaf " +
                "templates, so it survives only while input.css scans that directory — check the " +
                "@source globs there and the matching inputs on buildTailwind in build.gradle.kts."
        )
    }

    /** Tailwind escapes the characters that are not legal bare in a CSS selector. */
    private fun cssEscape(className: String): String =
        className.replace(Regex("""([\[\]./:#%!])"""), """\\$1""")
}
