package com.jankowski.rafal.dancebook.frontend

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource

/**
 * Guards the one Tailwind failure mode nothing else in this suite can see.
 *
 * Tailwind emits a rule only for class names it finds in a scanned source. Every rendering
 * test here asserts on HTML, which a CSS-generation regression leaves untouched — so if
 * `output.css` silently loses a class, the calendar chips render unstyled and the whole
 * build is still green.
 *
 * The classes below are the ones with no second source of truth: they are built at runtime
 * in the `static/js` scripts or in Kotlin, and appear in no Thymeleaf template. They exist in the
 * stylesheet only because `input.css` names those directories in an `@source` glob. Delete
 * one of those globs and these are the assertions that fail.
 */
class TailwindOutputCssTest {

    private val css: String by lazy {
        val url = javaClass.getResource("/static/css/output.css")
            ?: error(
                "static/css/output.css is missing from the classpath. It is generated by the " +
                    "buildTailwind Gradle task, which processResources depends on — run ./gradlew build."
            )
        url.readText()
    }

    @Test
    fun `the stylesheet is built and non-trivial`() {
        assertTrue(
            css.length > 20_000,
            "output.css is only ${css.length} bytes, which means the Tailwind build produced a stub."
        )
    }

    @ParameterizedTest(name = "{0} survives into output.css")
    @ValueSource(
        strings = [
            // training-calendar.js builds every chip, day dot and agenda row by hand.
            "tc-chip", "tc-chip-struck", "tc-chip-time", "tc-chip-title", "tc-chip-styles",
            "tc-daydots", "tc-daydot", "tc-agenda-empty",
            // Utilities applied only from JS: main.js collapsibles, guided-figure-edit.js
            // toasts, training-calendar.js cancelled-session styling.
            "max-h-[1000px]", "max-h-[500px]", "line-through", "border-solid", "z-9999",
            // NotificationController renders the unread badge as an HTML string in Kotlin.
            "min-w-[18px]", "h-[18px]",
        ]
    )
    fun `a class built outside the templates still has a rule`(className: String) {
        assertTrue(
            css.contains(".${cssEscape(className)}"),
            "`$className` has no rule in output.css. It is generated outside the Thymeleaf " +
                "templates, so it survives only while input.css scans that directory — check the " +
                "@source globs there and the matching inputs on buildTailwind in build.gradle.kts."
        )
    }

    @ParameterizedTest(name = "{0} was deleted and is absent from output.css")
    @ValueSource(
        strings = [
            "btn-lg", "card-hover", "card-interactive", "avatar", "avatar-sm", "avatar-lg",
            "nav-item", "nav-item-active", "nav-icon", "toast", "toast-success", "toast-error",
            "star", "star-filled", "sidebar", "sidebar-logo", "sidebar-nav", "sidebar-footer",
            "bottom-nav", "bottom-nav-item", "bottom-nav-icon", "bottom-nav-add",
            "modal-backdrop", "text-gradient", "scrollbar-hide"
        ]
    )
    fun `dead utilities are absent from output css`(className: String) {
        val classSelectorRegex = Regex("""\.${cssEscape(className)}(?=[^a-zA-Z0-9_-]|$)""")
        assertFalse(
            classSelectorRegex.containsMatchIn(css),
            "`$className` should have been deleted from input.css but is still present in output.css."
        )
    }

    @ParameterizedTest(name = "type token {0} is emitted in output.css")
    @ValueSource(
        strings = [
            "var(--text-title)",
            "var(--text-section)",
            "var(--text-meta)",
            "var(--text-tabular)",
            "var(--text-prose)"
        ]
    )
    fun `type tokens are emitted in output css`(token: String) {
        assertTrue(
            css.contains(token),
            "Expected output.css to contain type token reference `$token`."
        )
    }

    @Test
    fun `btn-outline uses outline border rather than outline-variant`() {
        val btnOutlineRegex = Regex("""\.btn-outline\s*\{[^}]*var\(--color-outline\)[^}]*\}""")
        assertTrue(
            btnOutlineRegex.containsMatchIn(css),
            ".btn-outline must use var(--color-outline) border token."
        )
    }

    @Test
    fun `card component uses surface and outline-variant tokens`() {
        val cardRegex = Regex("""\.card\s*\{[^}]*var\(--color-outline-variant\)[^}]*\}""")
        assertTrue(
            cardRegex.containsMatchIn(css),
            ".card must use var(--color-outline-variant) token."
        )
    }

    @Test
    fun `badge-warning component is emitted in output css`() {
        assertTrue(
            css.contains(".badge-warning"),
            "Expected output.css to contain .badge-warning rule."
        )
    }

    @Test
    fun `view switcher utilities survive into output css`() {
        assertTrue(
            css.contains(".view-switcher"),
            "Expected output.css to contain .view-switcher rule."
        )
        assertTrue(
            css.contains(".view-switcher-item"),
            "Expected output.css to contain .view-switcher-item rule."
        )
        assertTrue(
            css.contains(".view-switcher-item-active"),
            "Expected output.css to contain .view-switcher-item-active rule."
        )
        val itemTouchTargetRegex = Regex("""\.view-switcher-item\s*\{[^}]*min-height\s*:\s*44px[^}]*\}""")
        assertTrue(
            itemTouchTargetRegex.containsMatchIn(css),
            ".view-switcher-item must define 44px min-height touch target."
        )
    }

    @Test
    fun `pinned table utilities survive into output css`() {
        assertTrue(
            css.contains(".table-header-pinned"),
            "Expected output.css to contain .table-header-pinned rule."
        )
        assertTrue(
            css.contains(".table-cell-pinned"),
            "Expected output.css to contain .table-cell-pinned rule."
        )
    }

    @Test
    fun `pinned table utilities use required design tokens for opacity and seam`() {
        val headerRegex = Regex("""\.table-header-pinned\s*\{[^}]*var\(--color-surface-container\)[^}]*\}""")
        assertTrue(
            headerRegex.containsMatchIn(css),
            ".table-header-pinned must use var(--color-surface-container) token."
        )
        val rowRegex = Regex("""\.table-row\s*\{[^}]*var\(--color-surface\)[^}]*\}""")
        assertTrue(
            rowRegex.containsMatchIn(css),
            ".table-row must define opaque base background using var(--color-surface)."
        )
        val cellRegex = Regex("""\.table-cell-pinned\s*\{[^}]*background-color\s*:\s*inherit[^}]*\}""")
        assertTrue(
            cellRegex.containsMatchIn(css),
            ".table-cell-pinned must inherit background-color from its row."
        )
        val seamRegex = Regex("""\.table-cell-pinned\s*\{[^}]*var\(--color-outline-variant\)[^}]*\}""")
        assertTrue(
            seamRegex.containsMatchIn(css),
            ".table-cell-pinned must use var(--color-outline-variant) token for seam."
        )
    }

    @Test
    fun `table row and pinned cell utilities support dynamic row state tracking via inheritance`() {
        assertTrue(
            css.contains(".table-row:hover"),
            "Expected output.css to contain .table-row:hover rule for row hover highlight."
        )
        val cellInheritRegex = Regex("""\.table-cell-pinned\s*\{[^}]*background-color\s*:\s*inherit[^}]*\}""")
        assertTrue(
            cellInheritRegex.containsMatchIn(css),
            ".table-cell-pinned must use background-color: inherit to dynamically track row states."
        )
    }

    @Test
    fun `trix-editor and toolbar skin survive into output css`() {
        assertTrue(
            css.contains("trix-editor"),
            "Expected output.css to contain trix-editor rules from the unlayered skin."
        )
        assertTrue(
            css.contains("trix-toolbar"),
            "Expected output.css to contain trix-toolbar rules from the unlayered skin."
        )
    }

    @Test
    fun `rich-text prose list and link styles survive into output css`() {
        assertTrue(
            css.contains(".rich-text ul"),
            "Expected output.css to contain .rich-text ul bullet list styling."
        )
        assertTrue(
            css.contains(".rich-text ol"),
            "Expected output.css to contain .rich-text ol numbered list styling."
        )
        assertTrue(
            css.contains(".rich-text a"),
            "Expected output.css to contain .rich-text a link styling."
        )
    }

    @Test
    fun `toolbar icons use mask currentColor without hardcoded hex`() {
        assertFalse(
            css.contains("%2316181a"),
            "output.css should not contain hardcoded hex %2316181a in toolbar icons."
        )
    }

    /** Tailwind escapes the characters that are not legal bare in a CSS selector. */
    private fun cssEscape(className: String): String =
        className.replace(Regex("""([\[\]./:#%!])"""), """\\$1""")
}
