package com.jankowski.rafal.dancebook.frontend

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource

/**
 * Guards the one Tailwind failure mode nothing else in this suite can see.
 *
 * Tailwind emits a rule only for class names it finds in a scanned source. Every rendering
 * test here asserts on HTML, which a CSS-generation regression leaves untouched — so if
 * `output.css` silently loses a class, the calendar chips render unstyled and the whole
 * build is still green.
 *
 * The classes below are the ones with no second source of truth: they are built at runtime
 * in the `static/js` scripts or in Kotlin, and appear in no Thymeleaf template. They exist in the
 * stylesheet only because `input.css` names those directories in an `@source` glob. Delete
 * one of those globs and these are the assertions that fail.
 */
class TailwindOutputCssTest {

    private val css: String by lazy {
        val url = javaClass.getResource("/static/css/output.css")
            ?: error(
                "static/css/output.css is missing from the classpath. It is generated by the " +
                    "buildTailwind Gradle task, which processResources depends on — run ./gradlew build."
            )
        url.readText()
    }

    @Test
    fun `the stylesheet is built and non-trivial`() {
        assertTrue(
            css.length > 20_000,
            "output.css is only ${css.length} bytes, which means the Tailwind build produced a stub."
        )
    }

    @ParameterizedTest(name = "{0} survives into output.css")
    @ValueSource(
        strings = [
            // training-calendar.js builds every chip, day dot and agenda row by hand.
            "tc-chip", "tc-chip-struck", "tc-chip-time", "tc-chip-title", "tc-chip-styles",
            "tc-daydots", "tc-daydot", "tc-agenda-empty",
            // Utilities applied only from JS: main.js collapsibles, guided-figure-edit.js
            // toasts, training-calendar.js cancelled-session styling.
            "max-h-[1000px]", "max-h-[500px]", "line-through", "border-solid", "z-9999",
            // NotificationController renders the unread badge as an HTML string in Kotlin.
            "min-w-[18px]", "h-[18px]",
        ]
    )
    fun `a class built outside the templates still has a rule`(className: String) {
        assertTrue(
            css.contains(".${cssEscape(className)}"),
            "`$className` has no rule in output.css. It is generated outside the Thymeleaf " +
                "templates, so it survives only while input.css scans that directory — check the " +
                "@source globs there and the matching inputs on buildTailwind in build.gradle.kts."
        )
    }

    @ParameterizedTest(name = "{0} was deleted and is absent from output.css")
    @ValueSource(
        strings = [
            "btn-lg", "card-hover", "card-interactive", "avatar", "avatar-sm", "avatar-lg",
            "nav-item", "nav-item-active", "nav-icon", "toast", "toast-success", "toast-error",
            "star", "star-filled", "sidebar", "sidebar-logo", "sidebar-nav", "sidebar-footer",
            "bottom-nav", "bottom-nav-item", "bottom-nav-icon", "bottom-nav-add",
            "modal-backdrop", "text-gradient", "scrollbar-hide"
        ]
    )
    fun `dead utilities are absent from output css`(className: String) {
        val classSelectorRegex = Regex("""\.${cssEscape(className)}(?=[^a-zA-Z0-9_-]|$)""")
        assertFalse(
            classSelectorRegex.containsMatchIn(css),
            "`$className` should have been deleted from input.css but is still present in output.css."
        )
    }

    @ParameterizedTest(name = "type token {0} is emitted in output.css")
    @ValueSource(
        strings = [
            "var(--text-title)",
            "var(--text-section)",
            "var(--text-meta)",
            "var(--text-tabular)",
            "var(--text-prose)"
        ]
    )
    fun `type tokens are emitted in output css`(token: String) {
        assertTrue(
            css.contains(token),
            "Expected output.css to contain type token reference `$token`."
        )
    }

    @Test
    fun `btn-outline uses outline border rather than outline-variant`() {
        val btnOutlineRegex = Regex("""\.btn-outline\s*\{[^}]*var\(--color-outline\)[^}]*\}""")
        assertTrue(
            btnOutlineRegex.containsMatchIn(css),
            ".btn-outline must use var(--color-outline) border token."
        )
    }

    @Test
    fun `card component uses surface and outline-variant tokens`() {
        val cardRegex = Regex("""\.card\s*\{[^}]*var\(--color-outline-variant\)[^}]*\}""")
        assertTrue(
            cardRegex.containsMatchIn(css),
            ".card must use var(--color-outline-variant) token."
        )
    }

    @ParameterizedTest(name = "radius token {0} is defined in output.css")
    @ValueSource(
        strings = [
            "--radius-pill:9999px",
            "--radius-field:24px",
            "--radius-card:16px",
            "--radius-inset:12px",
            "--radius-button:var(--radius-pill)",
            "--radius-lg:16px",
            "--radius-xl:16px",
        ]
    )
    fun `radius tokens from the rounded forms mock are emitted`(declaration: String) {
        assertTrue(
            Regex(Regex.escape(declaration) + "[;}]").containsMatchIn(css.replace(" ", "")),
            "Expected output.css to define `$declaration`, the radius ladder from #214."
        )
    }

    @ParameterizedTest(name = "{0} is a pill")
    @ValueSource(
        strings = ["btn-primary", "btn-secondary", "btn-outline", "btn-danger", "btn-ghost", "btn-icon", "btn-sm", "form-input", "form-select"]
    )
    fun `buttons and single-line controls resolve to the pill radius`(className: String) {
        val rule = Regex("""\.${cssEscape(className)}\s*\{[^}]*border-radius\s*:\s*var\(--radius-pill\)[^}]*\}""")
        assertTrue(
            rule.containsMatchIn(css),
            "`$className` must take its corners from var(--radius-pill)."
        )
    }

    @Test
    fun `textarea uses the field radius and not the pill`() {
        val rules = Regex("""\.form-textarea\s*\{[^}]*\}""").findAll(css).map { it.value }.toList()
        val lastRadius = rules.flatMap { Regex("""border-radius\s*:\s*([^;}]+)""").findAll(it).map { m -> m.groupValues[1].trim() }.toList() }.last()
        assertTrue(
            lastRadius == "var(--radius-field)",
            ".form-textarea must end on var(--radius-field) so it wins over the pill it inherits, but ends on $lastRadius."
        )
    }

    @Test
    fun `multiple select uses the field radius and drops the dropdown chevron`() {
        val multipleRule = Regex("""\.form-select:is\([^{]*multiple[^{]*\)\s*\{[^}]*\}""").find(css)?.value
            ?: error("Expected output.css to contain a rule for .form-select:is([multiple]...)")
        assertTrue(
            multipleRule.contains("border-radius:var(--radius-field)"),
            "Multiple select must use var(--radius-field), but got: $multipleRule"
        )
        assertFalse(
            multipleRule.contains("var(--radius-pill)"),
            "Multiple select must not resolve to var(--radius-pill)"
        )
        assertTrue(
            multipleRule.contains("background-image:none"),
            "Multiple select must remove the dropdown chevron with background-image:none"
        )
    }

    @Test
    fun `card corners come from the card radius token`() {
        assertTrue(
            Regex("""\.card\s*\{[^}]*border-radius\s*:\s*var\(--radius-card\)[^}]*\}""").containsMatchIn(css),
            ".card must use var(--radius-card), 16px."
        )
        assertTrue(
            css.contains(".rounded-card") && css.contains("border-radius:var(--radius-card)"),
            "The rounded-card utility must exist so dialogs can name the token."
        )
    }

    @Test
    fun `form controls draw a 3px primary ring on focus that follows the curve`() {
        val focusRule = Regex("""\.form-input:focus\s*\{[^}]*\}""").findAll(css).joinToString("") { it.value }
        assertTrue(focusRule.contains("calc(3px + var(--tw-ring-offset-width))"), "Focus ring on .form-input must be 3px wide.")
        assertTrue(focusRule.contains("var(--color-primary) 22%"), "Focus ring on .form-input must be primary at 22%.")
    }

    @Test
    fun `global keyboard focus ring leaves form controls to their own ring`() {
        assertTrue(
            css.contains(":focus-visible:not(.form-input,.form-select,.form-textarea)") ||
                css.contains(":focus-visible:not(.form-input, .form-select, .form-textarea)"),
            "The global *:focus-visible rule must exclude form controls, or its !important 2px ring replaces the 3px one."
        )
    }

    @Test
    fun `invalid state turns the border and the focus ring to error and survives hover`() {
        val invalid = Regex("""\.form-input-invalid(:focus)?\s*\{[^}]*\}""").findAll(css).joinToString("") { it.value }
        assertTrue(invalid.contains("border-color:var(--color-error)!important"), "Invalid border must be error and !important so hover cannot repaint it.")
        assertTrue(invalid.contains("var(--color-error) 20%"), "Invalid focus ring must be error at 20%.")
    }

    @Test
    fun `disabled form controls are half opacity and ignore hover`() {
        assertTrue(
            Regex("""\.form-input:disabled\s*\{[^}]*opacity\s*:\s*\.5[^}]*\}""").containsMatchIn(css),
            ".form-input:disabled must be 50% opacity."
        )
        assertTrue(
            Regex("""\.form-input:disabled:hover\s*\{[^}]*\}""").containsMatchIn(css),
            ".form-input:disabled:hover must reset the hover lift."
        )
    }

    @Test
    fun `badge-warning component is emitted in output css`() {
        assertTrue(
            css.contains(".badge-warning"),
            "Expected output.css to contain .badge-warning rule."
        )
    }

    @Test
    fun `view switcher utilities survive into output css`() {
        assertTrue(
            css.contains(".view-switcher"),
            "Expected output.css to contain .view-switcher rule."
        )
        assertTrue(
            css.contains(".view-switcher-item"),
            "Expected output.css to contain .view-switcher-item rule."
        )
        assertTrue(
            css.contains(".view-switcher-item-active"),
            "Expected output.css to contain .view-switcher-item-active rule."
        )
        val itemTouchTargetRegex = Regex("""\.view-switcher-item\s*\{[^}]*min-height\s*:\s*44px[^}]*\}""")
        assertTrue(
            itemTouchTargetRegex.containsMatchIn(css),
            ".view-switcher-item must define 44px min-height touch target."
        )
    }

    @Test
    fun `pinned table utilities survive into output css`() {
        assertTrue(
            css.contains(".table-header-pinned"),
            "Expected output.css to contain .table-header-pinned rule."
        )
        assertTrue(
            css.contains(".table-cell-pinned"),
            "Expected output.css to contain .table-cell-pinned rule."
        )
    }

    @Test
    fun `pinned table utilities use required design tokens for opacity and seam`() {
        val headerRegex = Regex("""\.table-header-pinned\s*\{[^}]*var\(--color-surface-container\)[^}]*\}""")
        assertTrue(
            headerRegex.containsMatchIn(css),
            ".table-header-pinned must use var(--color-surface-container) token."
        )
        val rowRegex = Regex("""\.table-row\s*\{[^}]*var\(--color-surface\)[^}]*\}""")
        assertTrue(
            rowRegex.containsMatchIn(css),
            ".table-row must define opaque base background using var(--color-surface)."
        )
        val cellRegex = Regex("""\.table-cell-pinned\s*\{[^}]*background-color\s*:\s*inherit[^}]*\}""")
        assertTrue(
            cellRegex.containsMatchIn(css),
            ".table-cell-pinned must inherit background-color from its row."
        )
        val seamRegex = Regex("""\.table-cell-pinned\s*\{[^}]*var\(--color-outline-variant\)[^}]*\}""")
        assertTrue(
            seamRegex.containsMatchIn(css),
            ".table-cell-pinned must use var(--color-outline-variant) token for seam."
        )
    }

    @Test
    fun `table row and pinned cell utilities support dynamic row state tracking via inheritance`() {
        assertTrue(
            css.contains(".table-row:hover"),
            "Expected output.css to contain .table-row:hover rule for row hover highlight."
        )
        val cellInheritRegex = Regex("""\.table-cell-pinned\s*\{[^}]*background-color\s*:\s*inherit[^}]*\}""")
        assertTrue(
            cellInheritRegex.containsMatchIn(css),
            ".table-cell-pinned must use background-color: inherit to dynamically track row states."
        )
    }

    @Test
    fun `trix-editor and toolbar skin survive into output css`() {
        assertTrue(
            css.contains("trix-editor"),
            "Expected output.css to contain trix-editor rules from the unlayered skin."
        )
        assertTrue(
            css.contains("trix-toolbar"),
            "Expected output.css to contain trix-toolbar rules from the unlayered skin."
        )
    }

    @Test
    fun `rich-text prose list and link styles survive into output css`() {
        assertTrue(
            css.contains(".rich-text ul"),
            "Expected output.css to contain .rich-text ul bullet list styling."
        )
        assertTrue(
            css.contains(".rich-text ol"),
            "Expected output.css to contain .rich-text ol numbered list styling."
        )
        assertTrue(
            css.contains(".rich-text a"),
            "Expected output.css to contain .rich-text a link styling."
        )
    }

    @Test
    fun `toolbar icons use mask currentColor without hardcoded hex`() {
        assertFalse(
            css.contains("%2316181a"),
            "output.css should not contain hardcoded hex %2316181a in toolbar icons."
        )
    }

    @Test
    fun `trix-editor uses field radius and prose font`() {
        val editorRules = Regex("""trix-editor\s*\{[^}]*\}""").findAll(css).map { it.value }.toList()
        val radiusMatch = editorRules.any { it.contains("border-radius:var(--radius-field)") }
        assertTrue(
            radiusMatch,
            "trix-editor must define border-radius: var(--radius-field)."
        )
        val fontMatch = editorRules.any { it.contains("var(--font-prose)") }
        assertTrue(
            fontMatch,
            "trix-editor must use var(--font-prose)."
        )
    }

    @Test
    fun `trix-toolbar button groups and buttons use pill radius`() {
        val groupRule = Regex("""trix-toolbar \.trix-button-group\s*\{[^}]*\}""").find(css)?.value
            ?: error("Expected output.css to contain a rule for trix-toolbar .trix-button-group")
        assertTrue(
            groupRule.contains("border-radius:var(--radius-pill)"),
            "trix-toolbar .trix-button-group must use var(--radius-pill)."
        )
        val buttonRule = Regex("""trix-toolbar \.trix-button\s*\{[^}]*\}""").find(css)?.value
            ?: error("Expected output.css to contain a rule for trix-toolbar .trix-button")
        assertTrue(
            buttonRule.contains("border-radius:var(--radius-pill)"),
            "trix-toolbar .trix-button must use var(--radius-pill)."
        )
    }

    @Test
    fun `trix link dialog uses field radius and pill input`() {
        val dialogRule = Regex("""trix-toolbar \.trix-dialog\s*\{[^}]*\}""").find(css)?.value
            ?: error("Expected output.css to contain a rule for trix-toolbar .trix-dialog")
        assertTrue(
            dialogRule.contains("border-radius:var(--radius-field)"),
            "trix-toolbar .trix-dialog must use var(--radius-field)."
        )
        val inputRule = Regex("""trix-toolbar \.trix-input--dialog\s*\{[^}]*\}""").find(css)?.value
            ?: error("Expected output.css to contain a rule for trix-toolbar .trix-input--dialog")
        assertTrue(
            inputRule.contains("border-radius:var(--radius-pill)"),
            "trix-toolbar .trix-input--dialog must use var(--radius-pill)."
        )
    }

    @Test
    fun `comment card and link pill utilities survive into output css`() {
        val commentCardRules = Regex("""\.comment-card\s*\{[^}]*\}""").findAll(css).joinToString("") { it.value }
        assertTrue(
            commentCardRules.isNotEmpty(),
            "Expected output.css to contain a rule for .comment-card"
        )
        assertTrue(
            commentCardRules.contains("border-radius:var(--radius-field)"),
            ".comment-card must define border-radius: var(--radius-field)."
        )
        assertTrue(
            commentCardRules.contains("border-top-left-radius:var(--radius-inset)"),
            ".comment-card must define border-top-left-radius: var(--radius-inset)."
        )
        val linkPillRule = Regex("""\.link-pill\s*\{[^}]*\}""").find(css)?.value
            ?: error("Expected output.css to contain a rule for .link-pill")
        assertTrue(
            linkPillRule.contains("border-radius:var(--radius-pill)"),
            ".link-pill must use var(--radius-pill)."
        )
    }

    /** Tailwind escapes the characters that are not legal bare in a CSS selector. */
    private fun cssEscape(className: String): String =
        className.replace(Regex("""([\[\]./:#%!])"""), """\\$1""")
}
