
spring.application.name=DanceBook

spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.threads.virtual.enabled=true

# Google Drive - User OAuth for direct uploads
google.drive.client-id=918960884147-07oveb2kigr9g7s86kufd6rs5o4sbh8s.apps.googleusercontent.com
google.drive.folder-id=1dzi-Xte_5Ow_ojlN8gi_cr_3IhVFJrSV